server:
  port: 8098


app:
  dbros:
    datasource:
      username: db2admin
      password: db2admin
      url: jdbc:db2://10.41.0.35:50000/ROS

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#    generate-ddl: false
#    show-sql: true